/**
 * Single source of truth for seed products — uniform pricing, specs, colors, categories.
 * Images + long descriptions + technical specs come from productImages.js + productContent.js.
 */

const phone = (brand, ram, processor, storage, screen) => [
  { label: "Brand", value: brand },
  { label: "RAM", value: ram },
  { label: "Processor", value: processor },
  { label: "Storage", value: storage },
  { label: "Screen Size", value: screen },
];

const laptop = (brand, ram, processor, storage, gpu, screen) => [
  { label: "Brand", value: brand },
  { label: "RAM", value: ram },
  { label: "Processor", value: processor },
  { label: "Storage", value: storage },
  { label: "GPU Brand", value: gpu },
  { label: "Screen Size", value: screen },
];

/** categoryIndex: 0 smartphones … 7 accessories | subCategoryIndex: null or subCategories index */
export const PRODUCTS_CATALOG = [
  {
    name: "Galaxy S24 Ultra",
    price: 1199.99,
    discount: 100,
    quantity: 50,
    sold: 15,
    rating: 4.8,
    categoryIndex: 0,
    subCategoryIndex: 0,
    specs: phone("Samsung", "12GB", "Snapdragon 8 Gen 3", "256GB", "6.8"),
    colors: [
      { name: "Black", code: "#000000" },
      { name: "Blue", code: "#1e90ff" },
      { name: "Silver", code: "#c0c0c0" },
    ],
  },
  {
    name: "iPhone 15 Pro Max",
    price: 1299.99,
    discount: 150,
    quantity: 40,
    sold: 12,
    rating: 4.9,
    categoryIndex: 0,
    subCategoryIndex: 1,
    specs: phone("Apple", "8GB", "A17 Pro", "256GB", "6.7"),
    colors: [
      { name: "Titanium", code: "#878681" },
      { name: "Blue Titanium", code: "#4169e1" },
    ],
  },
  {
    name: "Google Pixel 8 Pro",
    price: 999.99,
    discount: 80,
    quantity: 32,
    sold: 9,
    rating: 4.7,
    categoryIndex: 0,
    subCategoryIndex: 0,
    specs: phone("Google", "12GB", "Tensor G3", "128GB", "6.7"),
    colors: [
      { name: "Obsidian", code: "#1a1a1a" },
      { name: "Porcelain", code: "#f5f5f5" },
    ],
  },
  {
    name: "Xiaomi 14",
    price: 799.99,
    discount: 60,
    quantity: 40,
    sold: 11,
    rating: 4.6,
    categoryIndex: 0,
    subCategoryIndex: 0,
    specs: phone("Xiaomi", "12GB", "Snapdragon 8 Gen 3", "256GB", "6.36"),
    colors: [
      { name: "Black", code: "#000000" },
      { name: "Green", code: "#2e8b57" },
    ],
  },
  {
    name: "MacBook Pro 16",
    price: 2499.99,
    discount: 200,
    quantity: 25,
    sold: 8,
    rating: 4.7,
    categoryIndex: 1,
    subCategoryIndex: 2,
    specs: laptop("Apple", "32GB", "M3 Max", "1TB", "Apple", "16.2"),
    colors: [{ name: "Space Gray", code: "#4d4d4d" }],
  },
  {
    name: "Dell XPS 15",
    price: 1799.99,
    discount: 120,
    quantity: 22,
    sold: 6,
    rating: 4.6,
    categoryIndex: 1,
    subCategoryIndex: 2,
    specs: laptop("Dell", "16GB", "Intel i7-13700H", "512GB", "NVIDIA", "15.6"),
    colors: [{ name: "Platinum", code: "#e5e4e2" }],
  },
  {
    name: "ASUS ROG Strix G16",
    price: 1899.99,
    discount: 150,
    quantity: 30,
    sold: 5,
    rating: 4.6,
    categoryIndex: 1,
    subCategoryIndex: 3,
    specs: laptop("ASUS", "16GB", "Intel i7-13700H", "512GB", "NVIDIA", "16"),
    colors: [{ name: "Black", code: "#000000" }],
  },
  {
    name: "iPad Pro 12.9",
    price: 1099.99,
    discount: 100,
    quantity: 35,
    sold: 10,
    rating: 4.8,
    categoryIndex: 2,
    subCategoryIndex: 4,
    specs: phone("Apple", "8GB", "M2", "256GB", "12.9"),
    colors: [
      { name: "Silver", code: "#c0c0c0" },
      { name: "Space Gray", code: "#4d4d4d" },
    ],
  },
  {
    name: "Samsung Galaxy Tab S9",
    price: 799.99,
    discount: 50,
    quantity: 28,
    sold: 7,
    rating: 4.5,
    categoryIndex: 2,
    subCategoryIndex: 5,
    specs: phone("Samsung", "8GB", "Snapdragon 8 Gen 2", "128GB", "11"),
    colors: [
      { name: "Black", code: "#000000" },
      { name: "Beige", code: "#f5f5dc" },
    ],
  },
  {
    name: "Sony WH-1000XM5",
    price: 399.99,
    discount: 50,
    quantity: 45,
    sold: 20,
    rating: 4.9,
    categoryIndex: 3,
    subCategoryIndex: 6,
    specs: [
      { label: "Brand", value: "Sony" },
      { label: "Type", value: "Wireless" },
      { label: "Noise Canceling", value: "Yes" },
    ],
    colors: [
      { name: "Black", code: "#000000" },
      { name: "Silver", code: "#c0c0c0" },
    ],
  },
  {
    name: "AirPods Pro 2",
    price: 249.99,
    discount: 25,
    quantity: 60,
    sold: 30,
    rating: 4.8,
    categoryIndex: 3,
    subCategoryIndex: 6,
    specs: [
      { label: "Brand", value: "Apple" },
      { label: "Type", value: "Wireless" },
      { label: "Noise Canceling", value: "Yes" },
    ],
    colors: [{ name: "White", code: "#ffffff" }],
  },
  {
    name: "Samsung Galaxy Buds3 Pro",
    price: 249.99,
    discount: 30,
    quantity: 55,
    sold: 22,
    rating: 4.5,
    categoryIndex: 3,
    subCategoryIndex: 6,
    specs: [
      { label: "Brand", value: "Samsung" },
      { label: "Type", value: "Wireless" },
      { label: "Noise Canceling", value: "Yes" },
    ],
    colors: [
      { name: "Silver", code: "#c0c0c0" },
      { name: "White", code: "#ffffff" },
    ],
  },
  {
    name: "Apple Watch Series 9",
    price: 399.99,
    discount: 40,
    quantity: 40,
    sold: 15,
    rating: 4.7,
    categoryIndex: 4,
    subCategoryIndex: null,
    specs: [
      { label: "Brand", value: "Apple" },
      { label: "Screen Size", value: "45mm" },
      { label: "Water Resistance", value: "50m" },
    ],
    colors: [
      { name: "Midnight", code: "#191970" },
      { name: "Starlight", code: "#f5f5dc" },
      { name: "Product Red", code: "#ff0000" },
    ],
  },
  {
    name: "Garmin Fenix 7",
    price: 699.99,
    discount: 50,
    quantity: 28,
    sold: 8,
    rating: 4.8,
    categoryIndex: 4,
    subCategoryIndex: null,
    specs: [
      { label: "Brand", value: "Garmin" },
      { label: "Screen Size", value: "47mm" },
      { label: "GPS", value: "Multi-band" },
    ],
    colors: [{ name: "Slate", code: "#708090" }],
  },
  {
    name: "Canon EOS R5",
    price: 3899.99,
    discount: 300,
    quantity: 15,
    sold: 3,
    rating: 4.9,
    categoryIndex: 5,
    subCategoryIndex: null,
    specs: [
      { label: "Brand", value: "Canon" },
      { label: "Sensor", value: "45MP Full-frame" },
      { label: "Video", value: "8K RAW" },
    ],
    colors: [{ name: "Black", code: "#000000" }],
  },
  {
    name: "PlayStation 5",
    price: 499.99,
    discount: 0,
    quantity: 20,
    sold: 50,
    rating: 4.8,
    categoryIndex: 6,
    subCategoryIndex: null,
    specs: [
      { label: "Brand", value: "Sony" },
      { label: "Storage", value: "825GB SSD" },
      { label: "GPU", value: "AMD RDNA 2" },
    ],
    colors: [{ name: "White", code: "#ffffff" }],
  },
  {
    name: "Xbox Series X",
    price: 499.99,
    discount: 0,
    quantity: 18,
    sold: 45,
    rating: 4.7,
    categoryIndex: 6,
    subCategoryIndex: null,
    specs: [
      { label: "Brand", value: "Microsoft" },
      { label: "Storage", value: "1TB SSD" },
      { label: "GPU", value: "12 TFLOPs" },
    ],
    colors: [{ name: "Black", code: "#000000" }],
  },
  {
    name: "Nintendo Switch OLED",
    price: 349.99,
    discount: 20,
    quantity: 35,
    sold: 28,
    rating: 4.8,
    categoryIndex: 6,
    subCategoryIndex: null,
    specs: [
      { label: "Brand", value: "Nintendo" },
      { label: "Storage", value: "64GB" },
      { label: "Screen Size", value: "7" },
    ],
    colors: [
      { name: "White", code: "#ffffff" },
      { name: "Neon", code: "#ff6b6b" },
    ],
  },
  {
    name: "MagSafe Charger 15W",
    price: 39.99,
    discount: 5,
    quantity: 120,
    sold: 85,
    rating: 4.4,
    categoryIndex: 7,
    subCategoryIndex: null,
    specs: [
      { label: "Brand", value: "Apple" },
      { label: "Power", value: "15W" },
      { label: "Type", value: "MagSafe" },
    ],
    colors: [{ name: "White", code: "#ffffff" }],
  },
  {
    name: "Logitech MX Master 3S",
    price: 99.99,
    discount: 10,
    quantity: 80,
    sold: 40,
    rating: 4.7,
    categoryIndex: 7,
    subCategoryIndex: null,
    specs: [
      { label: "Brand", value: "Logitech" },
      { label: "Connectivity", value: "Bluetooth / USB" },
      { label: "DPI", value: "8000" },
    ],
    colors: [
      { name: "Graphite", code: "#4d4d4d" },
      { name: "Pale Gray", code: "#d3d3d3" },
    ],
  },
];

export function resolveCatalogProduct(entry, categories, subCategories) {
  return {
    name: entry.name,
    price: entry.price,
    discount: entry.discount,
    quantity: entry.quantity,
    sold: entry.sold,
    rating: entry.rating,
    specs: entry.specs,
    color: JSON.stringify(entry.colors),
    category_id: categories[entry.categoryIndex].id,
    sub_category_id:
      entry.subCategoryIndex != null
        ? subCategories[entry.subCategoryIndex].id
        : null,
  };
}
